import { gsap } from "gsap";
import { GSDevTools } from "gsap/GSDevTools";
import { MorphSVGPlugin } from "gsap/MorphSVGPlugin";
import {CustomEase} from "gsap/CustomEase";

gsap.registerPlugin(GSDevTools, MorphSVGPlugin, CustomEase);
const mainTL = gsap.timeline();


function PreLoader(){
    const tl = gsap.timeline();

    tl.from ("svg",{duration: 2, x:"-=1000"});

    tl.to("#Hand0", {morphSVG:"#Hand1", duration: .02})
    .to("#Hand0", {morphSVG:"#Hand2", duration: .02})
    .to("#Hand0", {morphSVG:"#Hand3", duration: .02})
    .to("#Hand0", {morphSVG:"#Hand4", duration: .02})
    .to("#Hand0", {morphSVG:"#Hand5", duration: .03})
    .to("#Hand0", {morphSVG:"#Hand6", duration: .03})
    .to("#Hand0", {morphSVG:"#Hand7", duration: .03})
    .to("#Hand0", {morphSVG:"#Hand8", duration: .03})
    .to("#Hand0", {morphSVG:"#Hand9", duration: .02})

    .to ("#Button",{duration: .4, y:"2", ease: CustomEase.create("custom", "M0,0 C0.354,0.5 0.352,0.5 0.352,0.5 0.352,0.5 0.804,0.032 1,0 ")}, "-=.05")

    .to("#Hand0", {morphSVG:"#Hand10", duration: .04}, "-=.15")
    .to("#Hand0", {morphSVG:"#Hand11", duration: .04})
    .to("#Hand0", {y:"+=20px", x:"+=25", duration: .04});

    tl.from("#WhiteScreen", {scaleX:0, transformOrigin:"50% 50%", duration: .05, ease: "circ.out"}, "-=.3")
    .to("#BlackScreen", {alpha:0, duration: .01})
    .to("#WhiteScreen", {alpha:0, duration: .9})

    .to("#ArmR", {morphSVG:"#ArmR_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RForearm2", {morphSVG:"#RForearm2_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RForearm1", {morphSVG:"#RForearm1_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_1", duration: .05}, "SkeletonInMotion_1")
    .to("#RWrist", {morphSVG:"#RWrist_1", duration: .05}, "SkeletonInMotion_1")

    .to("#ArmR", {morphSVG:"#ArmR_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RForearm2", {morphSVG:"#RForearm2_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RForearm1", {morphSVG:"#RForearm1_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_2", duration: .05}, "SkeletonInMotion_2")
    .to("#RWrist", {morphSVG:"#RWrist_2", duration: .05}, "SkeletonInMotion_2")
    
    .to("#ArmR", {morphSVG:"#ArmR_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RForearm2", {morphSVG:"#RForearm2_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RForearm1", {morphSVG:"#RForearm1_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_3", duration: .05}, "SkeletonInMotion_3")
    .to("#RWrist", {morphSVG:"#RWrist_3", duration: .05}, "SkeletonInMotion_3")

    .to("#ArmR", {morphSVG:"#ArmR_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RForearm2", {morphSVG:"#RForearm2_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RForearm1", {morphSVG:"#RForearm1_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_4", duration: .05}, "SkeletonInMotion_4")
    .to("#RWrist", {morphSVG:"#RWrist_4", duration: .05}, "SkeletonInMotion_4")
    
    .to("#ArmR", {morphSVG:"#ArmR_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RForearm2", {morphSVG:"#RForearm2_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RForearm1", {morphSVG:"#RForearm1_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_5", duration: .05}, "SkeletonInMotion_5")
    .to("#RWrist", {morphSVG:"#RWrist_5", duration: .05}, "SkeletonInMotion_5")
    
    .to("#ArmR", {morphSVG:"#ArmR_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RForearm2", {morphSVG:"#RForearm2_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RForearm1", {morphSVG:"#RForearm1_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_6", duration: .05}, "SkeletonInMotion_6")
    .to("#RWrist", {morphSVG:"#RWrist_6", duration: .05}, "SkeletonInMotion_6")

    .to("#ArmR", {morphSVG:"#ArmR_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RForearm2", {morphSVG:"#RForearm2_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RForearm1", {morphSVG:"#RForearm1_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_7", duration: .05}, "SkeletonInMotion_7")
    .to("#RWrist", {morphSVG:"#RWrist_7", duration: .05}, "SkeletonInMotion_7")
    
    .to("#ArmR", {morphSVG:"#ArmR_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RForearm2", {morphSVG:"#RForearm2_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RForearm1", {morphSVG:"#RForearm1_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_8", duration: .05}, "SkeletonInMotion_8")
    .to("#RWrist", {morphSVG:"#RWrist_8", duration: .05}, "SkeletonInMotion_8")

    .to("#ArmR", {morphSVG:"#ArmR_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RForearm2", {morphSVG:"#RForearm2_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RForearm1", {morphSVG:"#RForearm1_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_9", duration: .05}, "SkeletonInMotion_9")
    .to("#RWrist", {morphSVG:"#RWrist_9", duration: .05}, "SkeletonInMotion_9")

    .to("#RForearm2", {morphSVG:"#RForearm2_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RForearm1", {morphSVG:"#RForearm1_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_10", duration: .05}, "SkeletonInMotion_10")
    .to("#RWrist", {morphSVG:"#RWrist_10", duration: .05}, "SkeletonInMotion_10")

    .to("#LForearm2", {morphSVG:"#LForearm2_11", duration: .05}, "+=.15", "SkeletonInMotion_11")
    .to("#LForearm1", {morphSVG:"#LForearm1_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LForearm2", {morphSVG:"#LForearm2_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerC5", {morphSVG:"#LFingerC5_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerC4", {morphSVG:"#LFingerC4_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerC3", {morphSVG:"#LFingerC3_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerC2", {morphSVG:"#LFingerC2_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerC1", {morphSVG:"#LFingerC1_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerB5", {morphSVG:"#LFingerB5_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerB4", {morphSVG:"#LFingerB4_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerB3", {morphSVG:"#LFingerB3_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerB2", {morphSVG:"#LFingerB2_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerB1", {morphSVG:"#LFingerB1_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerA5", {morphSVG:"#LFingerA5_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerA4", {morphSVG:"#LFingerA4_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerA3", {morphSVG:"#LFingerA3_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerA2", {morphSVG:"#LFingerA2_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LFingerA1", {morphSVG:"#LFingerA1_11", duration: .05}, "SkeletonInMotion_11")
    .to("#LWrist", {morphSVG:"#LWrist_11", duration: .05}, "SkeletonInMotion_11")
    
    .to("#ArmL", {morphSVG:"#ArmL_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LForearm2", {morphSVG:"#LForearm2_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LForearm1", {morphSVG:"#LForearm1_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerC5", {morphSVG:"#LFingerC5_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerC4", {morphSVG:"#LFingerC4_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerC3", {morphSVG:"#LFingerC3_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerC2", {morphSVG:"#LFingerC2_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerC1", {morphSVG:"#LFingerC1_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerB5", {morphSVG:"#LFingerB5_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerB4", {morphSVG:"#LFingerB4_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerB3", {morphSVG:"#LFingerB3_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerB2", {morphSVG:"#LFingerB2_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerB1", {morphSVG:"#LFingerB1_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerA5", {morphSVG:"#LFingerA5_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerA4", {morphSVG:"#LFingerA4_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerA3", {morphSVG:"#LFingerA3_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerA2", {morphSVG:"#LFingerA2_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LFingerA1", {morphSVG:"#LFingerA1_12", duration: .05}, "SkeletonInMotion_12")
    .to("#LWrist", {morphSVG:"#LWrist_12", duration: .05}, "SkeletonInMotion_12")

    .to("#ArmL", {morphSVG:"#ArmL_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LForearm2", {morphSVG:"#LForearm2_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LForearm1", {morphSVG:"#LForearm1_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerC5", {morphSVG:"#LFingerC5_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerC4", {morphSVG:"#LFingerC4_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerC3", {morphSVG:"#LFingerC3_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerC2", {morphSVG:"#LFingerC2_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerC1", {morphSVG:"#LFingerC1_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerB5", {morphSVG:"#LFingerB5_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerB4", {morphSVG:"#LFingerB4_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerB3", {morphSVG:"#LFingerB3_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerB2", {morphSVG:"#LFingerB2_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerB1", {morphSVG:"#LFingerB1_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerA5", {morphSVG:"#LFingerA5_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerA4", {morphSVG:"#LFingerA4_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerA3", {morphSVG:"#LFingerA3_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerA2", {morphSVG:"#LFingerA2_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LFingerA1", {morphSVG:"#LFingerA1_13", duration: .05}, "SkeletonInMotion_13")
    .to("#LWrist", {morphSVG:"#LWrist_13", duration: .05}, "SkeletonInMotion_13")

    .to("#ArmL", {morphSVG:"#ArmL_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LForearm2", {morphSVG:"#LForearm2_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LForearm1", {morphSVG:"#LForearm1_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerC5", {morphSVG:"#LFingerC5_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerC4", {morphSVG:"#LFingerC4_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerC3", {morphSVG:"#LFingerC3_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerC2", {morphSVG:"#LFingerC2_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerC1", {morphSVG:"#LFingerC1_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerB5", {morphSVG:"#LFingerB5_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerB4", {morphSVG:"#LFingerB4_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerB3", {morphSVG:"#LFingerB3_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerB2", {morphSVG:"#LFingerB2_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerB1", {morphSVG:"#LFingerB1_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerA5", {morphSVG:"#LFingerA5_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerA4", {morphSVG:"#LFingerA4_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerA3", {morphSVG:"#LFingerA3_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerA2", {morphSVG:"#LFingerA2_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LFingerA1", {morphSVG:"#LFingerA1_14", duration: .05}, "SkeletonInMotion_14")
    .to("#LWrist", {morphSVG:"#LWrist_14", duration: .05}, "SkeletonInMotion_14")

    .to("#ArmL", {morphSVG:"#ArmL_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LForearm2", {morphSVG:"#LForearm2_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LForearm1", {morphSVG:"#LForearm1_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerC5", {morphSVG:"#LFingerC5_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerC4", {morphSVG:"#LFingerC4_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerC3", {morphSVG:"#LFingerC3_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerC2", {morphSVG:"#LFingerC2_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerC1", {morphSVG:"#LFingerC1_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerB5", {morphSVG:"#LFingerB5_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerB4", {morphSVG:"#LFingerB4_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerB3", {morphSVG:"#LFingerB3_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerB2", {morphSVG:"#LFingerB2_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerB1", {morphSVG:"#LFingerB1_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerA5", {morphSVG:"#LFingerA5_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerA4", {morphSVG:"#LFingerA4_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerA3", {morphSVG:"#LFingerA3_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerA2", {morphSVG:"#LFingerA2_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LFingerA1", {morphSVG:"#LFingerA1_15", duration: .05}, "SkeletonInMotion_15")
    .to("#LWrist", {morphSVG:"#LWrist_15", duration: .05}, "SkeletonInMotion_15")

    .to("#ArmL", {morphSVG:"#ArmL_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LForearm2", {morphSVG:"#LForearm2_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LForearm1", {morphSVG:"#LForearm1_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerC5", {morphSVG:"#LFingerC5_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerC4", {morphSVG:"#LFingerC4_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerC3", {morphSVG:"#LFingerC3_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerC2", {morphSVG:"#LFingerC2_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerC1", {morphSVG:"#LFingerC1_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerB5", {morphSVG:"#LFingerB5_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerB4", {morphSVG:"#LFingerB4_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerB3", {morphSVG:"#LFingerB3_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerB2", {morphSVG:"#LFingerB2_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerB1", {morphSVG:"#LFingerB1_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerA5", {morphSVG:"#LFingerA5_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerA4", {morphSVG:"#LFingerA4_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerA3", {morphSVG:"#LFingerA3_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerA2", {morphSVG:"#LFingerA2_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LFingerA1", {morphSVG:"#LFingerA1_16", duration: .05}, "SkeletonInMotion_16")
    .to("#LWrist", {morphSVG:"#LWrist_16", duration: .05}, "SkeletonInMotion_16")

    .to("#ArmL", {morphSVG:"#ArmL_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LForearm2", {morphSVG:"#LForearm2_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LForearm1", {morphSVG:"#LForearm1_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerC5", {morphSVG:"#LFingerC5_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerC4", {morphSVG:"#LFingerC4_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerC3", {morphSVG:"#LFingerC3_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerC2", {morphSVG:"#LFingerC2_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerC1", {morphSVG:"#LFingerC1_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerB5", {morphSVG:"#LFingerB5_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerB4", {morphSVG:"#LFingerB4_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerB3", {morphSVG:"#LFingerB3_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerB2", {morphSVG:"#LFingerB2_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerB1", {morphSVG:"#LFingerB1_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerA5", {morphSVG:"#LFingerA5_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerA4", {morphSVG:"#LFingerA4_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerA3", {morphSVG:"#LFingerA3_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerA2", {morphSVG:"#LFingerA2_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LFingerA1", {morphSVG:"#LFingerA1_17", duration: .05}, "SkeletonInMotion_17")
    .to("#LWrist", {morphSVG:"#LWrist_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_17", duration: .05}, "SkeletonInMotion_17")
    .to("#RWrist", {morphSVG:"#RWrist_17", duration: .05}, "SkeletonInMotion_17")

    .to("#ArmL", {morphSVG:"#ArmL_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LForearm2", {morphSVG:"#LForearm2_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LForearm1", {morphSVG:"#LForearm1_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerC5", {morphSVG:"#LFingerC5_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerC4", {morphSVG:"#LFingerC4_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerC3", {morphSVG:"#LFingerC3_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerC2", {morphSVG:"#LFingerC2_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerC1", {morphSVG:"#LFingerC1_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerB5", {morphSVG:"#LFingerB5_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerB4", {morphSVG:"#LFingerB4_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerB3", {morphSVG:"#LFingerB3_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerB2", {morphSVG:"#LFingerB2_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerB1", {morphSVG:"#LFingerB1_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerA5", {morphSVG:"#LFingerA5_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerA4", {morphSVG:"#LFingerA4_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerA3", {morphSVG:"#LFingerA3_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerA2", {morphSVG:"#LFingerA2_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LFingerA1", {morphSVG:"#LFingerA1_18", duration: .1}, "SkeletonInMotion_18")
    .to("#LWrist", {morphSVG:"#LWrist_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_18", duration: .1}, "SkeletonInMotion_18")
    .to("#RWrist", {morphSVG:"#RWrist_18", duration: .1}, "SkeletonInMotion_18")

    .to("#LForearm2", {morphSVG:"#LForearm2_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LForearm1", {morphSVG:"#LForearm1_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerC5", {morphSVG:"#LFingerC5_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerC4", {morphSVG:"#LFingerC4_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerC3", {morphSVG:"#LFingerC3_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerC2", {morphSVG:"#LFingerC2_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerC1", {morphSVG:"#LFingerC1_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerB5", {morphSVG:"#LFingerB5_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerB4", {morphSVG:"#LFingerB4_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerB3", {morphSVG:"#LFingerB3_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerB2", {morphSVG:"#LFingerB2_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerB1", {morphSVG:"#LFingerB1_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerA5", {morphSVG:"#LFingerA5_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerA4", {morphSVG:"#LFingerA4_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerA3", {morphSVG:"#LFingerA3_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerA2", {morphSVG:"#LFingerA2_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LFingerA1", {morphSVG:"#LFingerA1_19", duration: .1}, "SkeletonInMotion_19")
    .to("#LWrist", {morphSVG:"#LWrist_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_19", duration: .1}, "SkeletonInMotion_19")
    .to("#RWrist", {morphSVG:"#RWrist_19", duration: .1}, "SkeletonInMotion_19")

    .to("#LFingerC5", {morphSVG:"#LFingerC5_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerC4", {morphSVG:"#LFingerC4_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerC3", {morphSVG:"#LFingerC3_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerC2", {morphSVG:"#LFingerC2_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerC1", {morphSVG:"#LFingerC1_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerB5", {morphSVG:"#LFingerB5_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerB4", {morphSVG:"#LFingerB4_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerB3", {morphSVG:"#LFingerB3_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerB2", {morphSVG:"#LFingerB2_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerB1", {morphSVG:"#LFingerB1_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerA5", {morphSVG:"#LFingerA5_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerA4", {morphSVG:"#LFingerA4_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerA3", {morphSVG:"#LFingerA3_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerA2", {morphSVG:"#LFingerA2_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LFingerA1", {morphSVG:"#LFingerA1_20", duration: .1}, "SkeletonInMotion_20")
    .to("#LWrist", {morphSVG:"#LWrist_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerD4", {morphSVG:"#RFingerD4_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerD3", {morphSVG:"#RFingerD3_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerD2", {morphSVG:"#RFingerD2_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerD1", {morphSVG:"#RFingerD1_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerC5", {morphSVG:"#RFingerC5_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerC4", {morphSVG:"#RFingerC4_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerC3", {morphSVG:"#RFingerC3_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerC2", {morphSVG:"#RFingerC2_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerC1", {morphSVG:"#RFingerC1_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerB5", {morphSVG:"#RFingerB5_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerB4", {morphSVG:"#RFingerB4_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerB3", {morphSVG:"#RFingerB3_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerB2", {morphSVG:"#RFingerB2_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerB1", {morphSVG:"#RFingerB1_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerA5", {morphSVG:"#RFingerA5_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerA4", {morphSVG:"#RFingerA4_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerA3", {morphSVG:"#RFingerA3_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerA2", {morphSVG:"#RFingerA2_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RFingerA1", {morphSVG:"#RFingerA1_20", duration: .1}, "SkeletonInMotion_20")
    .to("#RWrist", {morphSVG:"#RWrist_20", duration: .1}, "SkeletonInMotion_20")
    
    tl.to("#LightsOff", {autoAlpha:1, duration: .001}, "+=.05")
    .to("#preloader", {alpha:0, duration: .3, onComplete:removePreLoader}, "+=.5");

    return tl;
}

function removePreLoader(){
    window.scrollTo(0,0);
    gsap.set("#preloader", {display:"none"});
}

function Hero(){
    const tl = gsap.timeline();
    tl.from("header",{duration:.75, alpha:0, y:"+80"}, "-=30%")
      .from("h1",{duration:.75, alpha:0, y:"+70"}, "-=50%")
      .from("#hero_h2",{duration:.75, alpha:0, y:"+70"}, "-=90%")
      .from("#content_h2",{duration:.75, alpha:0, y:"+70"}, "-=60%")
      .from("h3",{duration:.6, alpha:0, y:"+70"}, "-=90%");

    return tl;
}

mainTL.add(PreLoader())
      .add(Hero());

// GSDevTools.create();